name: lit-components

on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  publish:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
       uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/

      - name: install node_modules
        run: npm install

      - name: build
        npx tsc && npx vite build

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
